name: setup-aseprite-cli-action
description: github action to build and install aseprite cli
branding:
  icon: terminal
  color: white
runs:
  using: composite
  steps:
  - id: prepare
    run: bash ./prepare.sh
    env:
      NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REPOSITORY: ${{ GITHUB.REPOSITORY }}
      NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REF: ${{ GITHUB.REF }}
  - id: cache
    uses: actions/cache@v2
    with:
      path: clone/bin
      key: ${{ runner.os }}-${{ steps.prepare.outputs.sha }}
  - run: ./build.sh
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
  - run: ./install.sh
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
